---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Initialize Packer Template
      - name: Initialize Packer Template
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          packer init "/home/runner/work/GitHub-Actions-Test/GitHub-Actions-Test/nginx"
        
      # Validate Packer Template
      - name: Validate Packer Template
        env:
         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          packer validate "/home/runner/work/GitHub-Actions-Test/GitHub-Actions-Test/nginx"
          pwd
          cat ${{ secrets.GOOGLE_CREDENTIALS }}
          
      # setup gcp service account
      - name: Gcloud Setup
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      # Build Packer Template
      - name: Build Packer Template
        run: packer build "/home/runner/work/GitHub-Actions-Test/GitHub-Actions-Test/nginx"
        env:
         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
